content:
  - name: show
    label: Émission
    path: src/public/assets/emission
    filename: "{fields.collection}-{fields.number}.json"
    format: json
    type: collection
    fields:
      - name: collection
        type: text
      - name: Number
        type: number