content:
  - name: show
    label: Émission
    path: src/public/assets/emission
    filename: "manifest.json"
    format: json
    type: collection
    fields:
      - name: title
        type: text
      - name: authors
        type: text
      - name: releasedAt
        type: date
      - name: type
        type: text
      - name: isPublic
        type: boolean
        default: false