backend_local: true

backend:
  name: github
  repo: constructions-incongrues/ouiedire
  branch: netlify
  site_domain: 1a522206-9642-4c26-bac4-280770cfbff4
  auth_scope: repo
  # open_authoring: true
  use_graphql: true
  squash_merges: true

media_folder: static/files
public_folder: /files

site_url: https://ouiedire.net
show_preview_links: true
# publish_mode: editorial_workflow

collections:
  - label: 'Emission'
    name: emission
    folder: data/emission
    create: true
    slug: '{{title}}'
    # preview_path: 'empilements/{{slug}}'
    path: '{{slug}}/manifest'
    extension: json
    format: json
    summary: "{{title}}"
    sortable_fields: [releasedAt, title]
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Release Date', name: 'releasedAt', widget: 'date' }
