backend:
  name: github
  repo: constructions-incongrues/ouiedire
  branch: netlify
  site_domain: 68f54904-001d-4ec7-bde3-4b2188078e16
  auth_scope: repo
  use_graphql: false
  squash_merges: true
  open_authoring: true

media_folder: ''
public_folder: /assets

site_url: https://demo.ouiedire.net
show_preview_links: true
publish_mode: editorial_workflow

collections:
  - label: 'Emission'
    description: "https://plesk.pastis-hosting.net/smb/file-manager/list/domainId/202"
    name: emission
    folder: src/public/emission
    media_folder: ''
    public_folder: ''
    create: true
    slug: '{{title}}'
    path: '{{type}}-{{number}}/manifest'
    preview_path: '/emission/{{type}}-{{number}}'
    extension: json
    format: json
    summary: "[{{type}}] #{{number}} - {{authors}} - {{title}}"
    sortable_fields: [releasedAt, title]
    view_filters:
      - label: Non Publié
        field: isPublic
        pattern: false
      - label: Ailleurs
        field: type
        pattern: ailleurs
      - label: Bagage
        field: type
        pattern: bagage
      - label: Bureau
        field: type
        pattern: bureau
      - label: Ouïedire
        field: type
        pattern: ouiedire
    view_groups:
      - label: Year
        field: releasedAt
        pattern: \d{4}
      - label: Type
        field: type
      - label: Authors
        field: authors
    fields:
      - {label: "Public ?", name: "isPublic", widget: "boolean", default: false}
      - label: "Type"
        name: "type"
        widget: "select"
        options:
        - { label: "Ailleurs", value: "ailleurs" }
        - { label: "Bagage", value: "bagage" }
        - { label: "Bureau", value: "bureau" }
        - { label: "Ouiedire", value: "ouiedire" }
      - { label: 'Number', name: 'number', widget: 'number' }
      - { label: 'Release Date', name: 'releasedAt', widget: 'date' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Authors', name: 'authors', widget: 'string' }
      - label: "Description"
        name: "description"
        widget: "code"
        default_language: HTML
      - label: "Playlist"
        name: "playlist"
        widget: "code"
        default_language: HTML
      # - label: "Tracks"
      #   name: "tracks"
      #   widget: "list"
      #   summary: '[{{fields.timecode}}] {{fields.title}} - {{fields.artists}}'
      #   fields:
      #     - {label: Timecode, name: timecode, widget: string}
      #     - {label: Title, name: title, widget: string}
      #     - label: Artists
      #       name: artists
      #       widget: list
      #       summary: '{{fields.name}}'
      #       fields:
      #         - label: Name
      #           name: name
      #           widget: string
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: false
        media_library:
          config:
            multiple: false
  # - label: 'Curator'
  #   name: curator
  #   folder: src/public/curator
  #   media_folder: ''
  #   public_folder: ''
  #   create: true
  #   slug: '{{name}}'
  #   path: '{{slug}}/manifest'
  #   identifier_field: name
  #   extension: json
  #   format: json
  #   summary: "{{name}}"
  #   sortable_fields: [name]
  #   fields:
  #     - {label: "Name", name: "name", widget: "string"}
  #     - {label: "URL", name: "url", widget: "string"}