backend_local: true

backend:
  name: github
  repo: constructions-incongrues/ouiedire
  branch: netlify
  site_domain: 1a522206-9642-4c26-bac4-280770cfbff4
  auth_scope: repo
  # open_authoring: true
  # use_graphql: true
  squash_merges: true

media_folder: ''
public_folder: /assets

site_url: https://ouiedire.net
show_preview_links: true
# publish_mode: editorial_workflow

collections:
  - label: 'Emission'
    name: emission
    folder: src/public/emission
    media_folder: ''
    public_folder: ''
    create: true
    slug: '{{title}}'
    path: '{{type}}-{{number}}/manifest'
    preview_path: /emission/{{type}}-{{number}}
    extension: json
    format: json
    summary: "{{type}} #{{number}} - {{authors}} - {{title}}"
    sortable_fields: [releasedAt, title]
    view_groups:
      - label: Year
        field: releasedAt
        pattern: \d{4}
      - label: Public
        field: isPublic
      - label: Type
        field: type
      - label: Authors
        field: authors
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Release Date', name: 'releasedAt', widget: 'date' }
      - { label: 'Authors', name: 'authors', widget: 'string' }
      - label: "Type"
        name: "type"
        widget: "select"
        options:
        - { label: "Ailleurs", value: "ailleurs" }
        - { label: "Bagage", value: "bagage" }
        - { label: "Bureau", value: "bureau" }
        - { label: "Ouiedire", value: "ouiedire" }
      - { label: 'Number', name: 'number', widget: 'number' }
      - {label: "Public ?", name: "isPublic", widget: "boolean", default: false}
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: false
        media_library:
          config:
            multiple: false
      - label: "Description"
        name: "description"
        widget: "code"
      - label: "Playlist"
        name: "playlist"
        widget: "code"
