# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Préparer une émission

on:
  workflow_dispatch:
    inputs:
      collection:
        type: choice
        default: Ailleurs
        options:
        - Ailleurs
        - Bagage
        - Bureau
        - Ouïedire
        required: true
      number:
        default: "999"
        required: true
        type: string
      title:
        type: string
        default: TODO
      authors:
        type: string
        default: TODO

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scaffold
        uses: andrewthetechie/gha-cookiecutter@v1.1.1
        with:
          template: ./src/skel/emission
          outputDir: ./src/public/assets/emission
          cookiecutterValues: |
            {
              "collection": "${{ inputs.collection }}",
              "title": "${{ inputs.title }}",
              "number": "${{ inputs.number }}",
              "authors": "${{ inputs.authors }}"
            }
      - name: Publish
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: './src/public/assets/emission'
          message: '${{ inputs.collection }}-${{ inputs.number }}'
          new_branch: ${{ inputs.collection }}-${{ inputs.number }}
